### PR TITLE
don't depend on sys.prefix as this is not valid in many scenarios

### PR DESCRIPTION
**Pull request by igkins**
right now if you deploy this to aws lambda or package it up as a zip for distribution, it'll fail because it depends on sys.prefix to locate the config.json instead of looking in its own package to locate it. That corrects the issue by including it in the package and then using importlib to properly locate/load the file.

### CODE REVIEW

**Comment by jamesliupenn** [comment]
@igkins thanks for the contribution, was busy and never saw this coming in 😭 

I'll review this soon and merge this for a later release update

**Comment by pccowboy** [comment]
@igkins Can you please provide an example of the error(s) this PR is meant to fix?  It'd be a lot easier for us to evaluate the PR if we had a clearer idea of your intent.  Please include details such as how you are packaging you lambda code package, so we can make sure we take that into account.

Thanks!

**Comment by igkins** [comment]
@pccowboy , try to deploy a lambda function on AWS using the onfleet, it won't be able to find config.json due to how AWS configures sys.prefix. In my case, we deployed using the serverless framework and the plugin serverless-python-requirements, though manually zipping the dependencies and deploying will also cause this issue

**Comment by jamesliupenn** [comment]
@igkins, thanks for the feedback. I've refactored the config file from a JSON to a Python module that comes with the library, this should resolve the issue that you are having while resolving directory issues reported by Windows users.

Would you mind taking a look at v1.1.0 and see if that fixes your problem?

**Comment by jamesliupenn** [comment]
@igkins I'm closing this issue as the recent config updates should've fixed the problem you were facing. Let us know if you still have more questions! Thanks for contributing!

**Pull request closed without merging**
